[2018-01-08 11:55:07] php.DEBUG: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"type":2,"file":"/Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2018-01-08 11:55:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
[2018-01-08 11:55:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php line 2380 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php:2380, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
[2018-01-08 11:58:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php line 2380 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php:2380, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
[2018-01-08 12:02:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php line 2380 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php:2380, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
[2018-01-08 12:02:44] request.INFO: Matched route "{route}". {"route":"post_login","route_parameters":{"_controller":"AppBundle\\Controller\\RestLoginController::postAction","_format":"json","_route":"post_login"},"request_uri":"http://127.0.0.1:8000/login","method":"POST"} []
[2018-01-08 12:02:44] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17 FROM fos_user t0 WHERE t0.username_canonical = ? LIMIT 1 ["peter"] []
[2018-01-08 12:02:44] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17 FROM fos_user t0 WHERE t0.username_canonical = ? LIMIT 1' with params [\"peter\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'code_review_db_rest_user_api.fos_user' doesn't exist at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:94, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.locked AS locked_9, t0.expired AS expired_10, t0.expires_at AS expires_at_11, t0.confirmation_token AS confirmation_token_12, t0.password_requested_at AS password_requested_at_13, t0.roles AS roles_14, t0.credentials_expired AS credentials_expired_15, t0.credentials_expire_at AS credentials_expire_at_16, t0.id AS id_17 FROM fos_user t0 WHERE t0.username_canonical = ? LIMIT 1' with params [\"peter\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'code_review_db_rest_user_api.fos_user' doesn't exist at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'code_review_db_rest_user_api.fos_user' doesn't exist at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'code_review_db_rest_user_api.fos_user' doesn't exist at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2018-01-08 12:03:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /app_acceptance/login"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php line 2380 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /app_acceptance/login\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php:2380, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
[2018-01-08 13:36:52] php.DEBUG: fsockopen(): unable to connect to 127.0.0.1:8000 (Connection refused) {"type":2,"file":"/Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/ServerCommand.php","line":59,"level":28928} []
[2018-01-08 13:36:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /app_acceptance/login"" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php line 2380 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /app_acceptance/login\" at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/classes.php:2380, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /Users/shaunthornburgh/Documents/Development/code_review_db_rest_user_api/var/cache/dev/appDevUrlMatcher.php:114)"} []
